(******************************************************************************)
(*                                                                            *)
(*                    New Model Army Organizational Structure                 *)
(*                                                                            *)
(*     Formalization of the 1645-1660 Parliamentary army: regiment/troop      *)
(*     hierarchy, pay scales by rank, promotion criteria (merit over birth),  *)
(*     Self-Denying Ordinance compliance, and command succession rules.       *)
(*     The first English standing army with standardized organization.        *)
(*                                                                            *)
(*     "I had rather have a plain, russet-coated Captain, that knows what     *)
(*      he fights for, and loves what he knows, than that which you call      *)
(*      a Gentle-man and is nothing else." - Oliver Cromwell, 1643            *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 14, 2026                                                 *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
